name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: macos-15
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: build
        run: |
          cd ${{ github.workspace }}
          sh build.sh
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: llvm
            # A file, directory or wildcard pattern that describes what to upload
          path: ${{ github.workspace }}/dist
                             
